# SPDX-FileCopyrightText: 2024 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure exim-relay base path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ exim_relay_uid }}"
    group: "{{ exim_relay_gid }}"
  with_items:
    - {path: "{{ exim_relay_base_path }}", when: true}
    - {path: "{{ exim_relay_container_image_self_build_src_files_path }}", when: "{{ exim_relay_container_image_self_build }}"}
  when: item.when | bool

- name: Ensure exim-relay spool path exists
  ansible.builtin.file:
    path: "{{ exim_relay_spool_path }}"
    state: directory
    mode: 0750
    owner: "{{ exim_relay_container_user_uid }}"
    group: "{{ exim_relay_container_user_gid }}"

- name: Ensure exim-relay environment variables file created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ exim_relay_base_path }}/env"
    mode: 0640

- name: Ensure exim-relay DKIM private key file created
  ansible.builtin.copy:
    content: "{{ exim_relay_dkim_privkey_contents }}"
    dest: "{{ exim_relay_dkim_privkey_path }}"
    mode: 0640
    owner: "{{ exim_relay_container_user_uid }}"
    group: "{{ exim_relay_container_user_gid }}"
  when: exim_relay_dkim_privkey_contents != "" and not exim_relay_relay_use|bool

- when: exim_relay_container_image_self_build | bool
  block:
    - name: Ensure exim-relay repository is present on self-build
      ansible.builtin.git:
        repo: "{{ exim_relay_container_image_self_build_repository_url }}"
        dest: "{{ exim_relay_container_image_self_build_src_files_path }}"
        version: "{{ exim_relay_container_image_self_build_version }}"
        force: "yes"
      become: true
      become_user: "{{ exim_relay_uid }}"
      register: exim_relay_git_pull_results

    - name: Ensure exim-relay Docker image is built
      community.docker.docker_image:
        name: "{{ exim_relay_container_image }}"
        source: build
        force_source: "{{ exim_relay_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else exim_relay_git_pull_results.changed }}"
        build:
          dockerfile: Dockerfile
          path: "{{ exim_relay_container_image_self_build_src_files_path }}"
          pull: true

- name: Ensure exim-relay image is pulled
  community.docker.docker_image:
    name: "{{ exim_relay_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ exim_relay_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else exim_relay_container_image_force_pull }}"
  when: "not exim_relay_container_image_self_build | bool"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure exim-relay container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ exim_relay_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure exim-relay.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/exim-relay.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ exim_relay_identifier }}.service"
    mode: 0644
