# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: (Deprecation) Catch and report renamed exim-relay variables
  ansible.builtin.fail:
    msg: >-
      The variable `{{ item.old }}` is deprecated. Please use `{{ item.new }}` instead.
  when: "item.old in vars"
  with_items:
    - {'old': 'exim_relay_container_image_name_prefix', 'new': 'exim_relay_container_image_registry_prefix'}

- name: Fail if required exim-relay settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == ''"
  with_items:
    - {'name': 'exim_relay_uid', when: true}
    - {'name': 'exim_relay_gid', when: true}
    - {'name': 'exim_relay_hostname', when: true}
    - {'name': 'exim_relay_sender_address', when: true}
    - {'name': 'exim_relay_container_network', when: true}
